# Generated by Django 5.0.3 on 2024-03-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='event_images')),
                ('start_prize', models.IntegerField(null=True)),
                ('mini_title', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
