# Generated by Django 5.0.3 on 2024-03-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_eventsclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsclass',
            name='mini_title',
        ),
        migrations.RemoveField(
            model_name='eventsclass',
            name='start_prize',
        ),
    ]
