# Generated by Django 5.0.3 on 2024-03-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_categories_event_des_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_location', models.CharField(max_length=120, null=True)),
                ('his_duration', models.IntegerField(null=True)),
                ('his_agency', models.CharField(max_length=200, null=True)),
                ('his_contact', models.CharField(max_length=12, null=True)),
                ('his_bill', models.IntegerField(null=True)),
                ('his_comp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='event_app.company')),
            ],
        ),
    ]
