# Generated by Django 5.0.3 on 2024-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='his_date',
            field=models.DateField(null=True),
        ),
    ]
