# Generated by Django 5.0.3 on 2024-04-03 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_history_his_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='his_comp',
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100, null=True)),
                ('comp_location', models.CharField(max_length=100, null=True)),
                ('comp_id', models.IntegerField(null=True)),
                ('comp_image', models.ImageField(null=True, upload_to='comp_images')),
                ('comp_contact', models.CharField(max_length=12, null=True)),
                ('comp_bio', models.TextField(null=True)),
                ('comp_agent', models.CharField(max_length=100, null=True)),
                ('comp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_type', to='event_app.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
