# Generated by Django 5.0.3 on 2024-04-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_remove_history_his_comp_companyprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='comp_id',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='comp_name',
        ),
    ]
