# Generated by Django 5.0.3 on 2024-04-08 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_alter_companyprofile_comp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='comp_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to='event_app.categories'),
        ),
    ]
