# Generated by Django 5.0.3 on 2024-04-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0012_alter_companyprofile_comp_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='comp_name',
        ),
    ]
