# Generated by Django 5.0.3 on 2024-04-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0021_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='consultation_request',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ConsultationRequest',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
