# Generated by Django 5.0.3 on 2024-04-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0023_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_company_user',
            field=models.BooleanField(default=False),
        ),
    ]
