# Generated by Django 5.0.3 on 2024-04-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0025_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
