# Generated by Django 5.0.3 on 2024-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0027_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
