# Generated by Django 5.0.3 on 2024-05-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0028_alter_booking_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
