# Generated by Django 5.0.3 on 2024-05-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0042_booking_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_read',
        ),
    ]
