# Generated by Django 5.0.3 on 2024-05-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0047_remove_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
