# Generated by Django 5.0.3 on 2024-05-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0050_remove_notification_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
