# Generated by Django 5.0.3 on 2024-05-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0052_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
