# Generated by Django 5.0.3 on 2024-05-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0053_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_unread',
            field=models.BooleanField(default=True),
        ),
    ]
