# Generated by Django 5.0.3 on 2024-05-10 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0055_remove_message_is_unread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField()),
                ('timestamp1', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages1', to=settings.AUTH_USER_MODEL)),
                ('sender1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
