# Generated by Django 5.0.3 on 2024-05-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0058_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
