# Generated by Django 5.0.3 on 2024-06-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0067_delete_unreadmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='event_type',
        ),
    ]
